### ISSUE TITLE
ACI pods get stuck in Pending phase with ProviderFailed reason

### ISSUE THREAD

**Issue by chrisdawww** [virtual-kubelet/virtual-kubelet#1257]
---

### Environment summary

Provider (e.g. ACI, AWS Fargate)
ACI

Version (e.g. 0.1, 0.2-beta)
v1.25.0-vk-azure-aci-1.6.1

K8s Master Info (e.g. AKS, ACS, Bare Metal, EKS)
AKS 
kubernetes version v1.30.4

Install Method (e.g. Helm Chart, )
Helm chart

### Issue Details

Intermittently the pod fails to find the image pull secret available in its namespace. When this happens, the pod falls into [this code](https://github.com/virtual-kubelet/virtual-kubelet/blob/1f5e83b1d679841ddfe7b57a0deedf3d40d90522/node/pod.go#L157) which sets the pod's phase to "Pending" and the reason to "ProviderFailed". Kubernetes will _never_ try to restart a pod in this non-terminated state. The pod will stay as Pending with the status "ProviderFailed" until manual intervention.

We should not set the pod to "Pending" in this failure state. This `handleProviderError` should always set the pod's phase to `corev1.PodFailed`

### Repro Steps

Create a dummy pod.yaml file to apply into the kubernetes cluster. Ensure the container specifies a non-existent kubernetes secret in the `imagePullSecrets`:
```
apiVersion: v1
kind: Pod
metadata:
  name: helloworld
spec:
  containers:
  - image: microsoft/aci-helloworld
    imagePullPolicy: Always
    name: helloworld
    imagePullSecrets:
    - name: this-secret-does-not-exist
    resources:
      requests:
        memory: 1G
        cpu: 1
    ports:
    - containerPort: 80
      name: http
      protocol: TCP
    - containerPort: 443
      name: https
  dnsPolicy: ClusterFirst
  nodeSelector:
    kubernetes.io/role: agent
    beta.kubernetes.io/os: linux
    type: virtual-kubelet
  tolerations:
  - key: virtual-kubelet.io/provider
    operator: Exists
  - key: azure.com/aci
    effect: NoSchedule
```
