### ISSUE TITLE
Controlling the location ACI instances are created in

### ISSUE THREAD

**Issue by brobichaud** [virtual-kubelet/virtual-kubelet#143]
---

### Environment summary
ACS cluster with Windows nodes, k8s v1.7.7-7. Windows Server 2016 RTM.

Provider (e.g. Azure, Hyper)
Azure

Version (e.g. 0.1, 0.2-beta)
microsoft/aci-connector-k8s:canary

K8s Master Info (e.g. AKS, ACS, Bare Metal)
ACS

Install Method (e.g. Helm Chart, )
kubectl & yaml

### Issue Details
All ACI instances created are in the WestUS region. How is this controlled?

### Repo Steps
Deploy a pod and the ACI is always in WestUS.

**Comment by robbiezhang** [comment]
@brobichaud, please use microsoft/virtual-kubelet:latest image.
You can set the environment variable ACI_REGION to your desired region.
https://github.com/virtual-kubelet/virtual-kubelet/blob/master/charts/virtual-kubelet/templates/deployment.yaml

I would also recommend you to use the Helm chart to install the VK. Here is the instruction:
https://github.com/virtual-kubelet/virtual-kubelet/blob/master/providers/azure/README.md#manual-set-up

**Comment by brobichaud** [comment]
@robbiezhang I've tried the ehlm install approach as the instructions reference AKS and I am using old-school ACS (because I need Windows nodes). It wasn't clear to me if I'd get myself into trouble with the AKS instructions. Do you think that would work with ACS?

Until I hear back I will move to the latest image and deployment.yaml you referenced (I was not using that, I was using the one Anthony shows in: https://anthonychu.ca/post/windows-containers-aci-connector-kubernetes/)

**Comment by robbiezhang** [comment]
The [link](https://github.com/virtual-kubelet/virtual-kubelet/blob/master/providers/azure/README.md#manual-set-up) contains the instruction about how to use Helm chart to install VK in any k8s cluster including ACS. Please take a look.

**Comment by robbiezhang** [comment]
You can add a node selector in the VK pod spec:
```
  nodeSelector:
    kubernetes.io/hostname: <your desired node name>
```
[Reference](https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#nodeselector)

**Comment by brobichaud** [comment]
Yeah I am familiar with nodeSelectors (I'd use beta.kubernetes.io/os: linux), but when using helm to deploy I don't seem to have access to the pod spec. How do I change that? Full disclosure: helm newbie

**Comment by robbiezhang** [comment]
I see. The chart doesn't set the nodeSelector. I'll add it now.
The Helm will create a deployment according to the Helm chart in your cluster. As a workaround, you can always edit the deployment to make it work for you.

**Comment by robbiezhang** [comment]
#146

**Comment by brobichaud** [comment]
Ah yes, manually updating the pod spec. Was aware of that option but had never needed to use it. Success, virtual-kubelet pod now running.

Thanks for the #146 update. Not knowing helm, does that pull request eventually end up in the chart referenced in the install instructions as: https://github.com/virtual-kubelet/virtual-kubelet/raw/master/charts/$VK_RELEASE.tgz ?

**Comment by brobichaud** [comment]
OK, as I continue down this journey of using the latest kubelet please tell me if you'd prefer a new issue created @robbiezhang.

I am now trying to deploy a Windows ACI and am having a hard time. Below is my pod spec. If I try and create this I see an immediate error in the k8s dashboard where the new pod has a bang icon and the tooltip is simply "this pod has errors". I don't know how to debug that other than trial and error. I've found if I rip out the entire "env" and "resources" sections that it deploys, I see the ACI get created. Do I have unsupported options in those sections?

```
apiVersion: v1
kind: Pod
metadata:
  name: worker
spec:
  imagePullSecrets:
    - name: discovercloud-registry
  dnsPolicy: ClusterFirst
  nodeName: virtual-kubelet
  tolerations:
  - key: azure.com/aci
    effect: NoSchedule
  containers:
  - image:  discovercloud.azurecr.io/fossil/worker/develop:develop.79
    imagePullPolicy: Always
    name: worker
    resources:
      requests:
        cpu: 2
        memory: 4G
    env:
    - name: CLOUD_DEPLOYMENT
      value: fossil
    - name: CLOUD_COMPONENT
      value: api
    - name: CLOUD_ENVIRONMENT
      value: dev
    - name: CLOUD_K8S_POD
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: CLOUD_K8S_NODE
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: CLOUD_KEYVAULT
      valueFrom:
        secretKeyRef:
          name: azure-keyvault
          key: keyvault-creds.dat
```

**Comment by robbiezhang** [comment]
Yes, #146 includes the Helm chart package update.
Your pod spec uses the k8s "Downward API" feature, which is not supported by VK yet.

```
    - name: CLOUD_K8S_POD
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: CLOUD_K8S_NODE
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
```
I believe the issue will be fixed if you can replace the "valueFrom: ..." to "value: ..." since you know their values (metadata.name => "worker", spec.nodeName => your VK node name)
To troubleshoot the issue, you can run `kubectl logs <vk pod>` or `kubectl describe po <your pod>` to see the details.

**Comment by brobichaud** [comment]
Indeed the Downward API env variables were causing a problem. I can work past those given your advice. Now when I use this resource request:

```
    resources:
      requests:
        cpu: 2
        memory: 4G
```

I see this error in the pod logs:

> Error creating pod 'worker': api call to https://management.azure.com/subscriptions/{subscription-id}/resourceGroups/dev-aci/providers/Microsoft.ContainerInstance/containerGroups/default-worker?api-version=2018-02-01-preview: got HTTP response status code 400 error code "ResourceLimitsLessThanRequests": The resource requirement '{"requests":{"memoryInGB":4.0,"cpu":2.0},"limits":{"memoryInGB":1.5,"cpu":1.0}}' in container 'worker' of contain group 'default-worker' is invalid. The 'Cpu' limit value must be greater than or equal to the request value.

So I though I should also add a limits using the resources section below:

```
    resources:
      requests:
        cpu: 2
        memory: 4G
      limits:
        cpu: 4
        memory: 14G
```
And I now see this error in the pod logs:

> Error creating pod 'worker': api call to https://management.azure.com/subscriptions/{subscription-id}/resourceGroups/dev-aci/providers/Microsoft.ContainerInstance/containerGroups/default-worker?api-version=2018-02-01-preview: got HTTP response status code 400 error code "ContainerLimitGreaterThanContainerGroupTotalRequest": The 'Cpu' limit '4' in container 'worker' is greater than the total request '2' of container group 'default-worker'.

This led me to one last experiment that actually worked. Any idea what's up?

```
    resources:
      requests:
        cpu: 4
        memory: 14G
      limits:
        cpu: 4
        memory: 14G
```
