### ISSUE TITLE
Using env.valueFrom instead of env.value breaks deployment on ACI

### ISSUE THREAD

**Issue by arjanschaaf** [virtual-kubelet/virtual-kubelet#174]
---

### Environment summary

Provider (e.g. Azure, Hyper)

Azure

Version (e.g. 0.1, 0.2-beta)

virtual-kubelet-for-aks-0.1.3

K8s Master Info (e.g. AKS, ACS, Bare Metal)

AKS

Install Method (e.g. Helm Chart, )

Helm Chart

### Issue Details

Instead of simply specifying an pod environment variable by its name & value:
```
    env:
      - name: hello
        value: world
```
you can also use the *valueFrom* For example to pass pod information to the container.
The following yaml will fail on deployment with the pod left in status *ProviderFailed* with the error message:
```
api call to https://management.azure.com/subscriptions/<ID>/resourceGroups/<ID>/providers/Microsoft.ContainerInstance/containerGroups/default-echoserver?api-version=2018-02-01-preview: got HTTP response status code 400 error code "InvalidRequestContent": The request content was invalid and could not be deserialized: 'Required property 'value' not found in JSON. Path 'properties.containers[0].properties.environmentVariables[0]', line 1, position 421.'.
```

```
apiVersion: v1
kind: Pod
metadata:
  name: echoserver
spec:
  containers:
  - image: gcr.io/google_containers/echoserver:1.10
    imagePullPolicy: Always
    name: echoserver
    resources:
      requests:
        memory: 1G
        cpu: 1
      limits:
        memory: 1G
        cpu: 1
    ports:
    - containerPort: 8080
    env:
      - name: NODE_NAME
        valueFrom:
          fieldRef:
            fieldPath: spec.nodeName
      - name: POD_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
      - name: POD_NAMESPACE
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
      - name: POD_IP
        valueFrom:
          fieldRef:
            fieldPath: status.podIP
  dnsPolicy: ClusterFirst
  nodeName: virtual-kubelet
  tolerations:
  - key: azure.com/aci
    effect: NoSchedule
```
### Repo Steps
1) kubectl create -f echoserver.yaml
2) kubectl get pod -> pod in status *ProviderFailed*
