### ISSUE TITLE
[Azure] Cannot get metrics from virtual kubelet (Unable to get metrics for resource cpu: no metrics returned from heapster)

### ISSUE THREAD

**Issue by Nalgmann** [virtual-kubelet/virtual-kubelet#228]
Hi! I hope you have a nice day. I'm having a detail:

### Environment summary

Provider: Azure

Version: `microsoft/virtual-kubelet:latest`, resolving to `0.3.2` at Jun-14

K8s Master Info: AKS, version `1.9.6`

Install Method: `helm install`, due to get logs from pods and nodes

Complete command: 
`$ helm install "$CHART_URL" --name "$RELEASE_NAME" --set env.azureClientId="$AZURE_CLIENT_ID",env.azureClientKey="$AZURE_CLIENT_SECRET",env.azureTenantId="$AZURE_TENANT_ID",env.azureSubscriptionId="$AZURE_SUBSCRIPTION_ID",env.aciRegion="$ACI_REGION",env.aciResourceGroup="$AZURE_RG",env.nodeName="$NODE_NAME",env.nodeOsType=Linux,env.apiserverCert=$cert,env.apiserverKey=$key,rbac.install=false`

`VK_RELEASE=virtual-kubelet-for-aks-0.1.3`
`CHART_URL=https://github.com/virtual-kubelet/virtual-kubelet/raw/master/charts/$VK_RELEASE.tgz`
`ACI_REGION=eastus`
`RELEASE_NAME=NODE_NAME=virtual-kubelet`

### Issue Details
I have a deploy I want to autoscale. I deploy it under my virtual node to get a container instance. I installed [metrics-server yamls](https://github.com/kubernetes-incubator/metrics-server/tree/master/deploy/1.8%2B) to get metrics and enable the sutoscale. The problem is that I do not get metrics information from neither the virtual kubelet's pod nor the virtual kubelet's node. 

Getting hpa I get the following:
```
$ kubectl get hpa
NAME                        REFERENCE           TARGETS         MINPODS   MAXPODS   REPLICAS      AGE
clientsv3-staging   Deployment/clientsv3-staging   <unknown>/50%   1         2         1          48m
```
Describing hpa I get this:
```
$ kubectl describe hpa clientsv3-staging
Name:                                                  clientsv3-staging
Namespace:                                             default
Labels:                                                <none>
Annotations:                                           <none>
CreationTimestamp:                                     Thu, 14 Jun 2018 16:53:01 -0500
Reference:                                             Deployment/clientsv3-staging
Metrics:                                               ( current / target )
  resource cpu on pods  (as a percentage of request):  <unknown> / 50%
Min replicas:                                          1
Max replicas:                                          2
Conditions:
  Type           Status  Reason                   Message
  ----           ------  ------                   -------
  AbleToScale    True    SucceededGetScale        the HPA controller was able to get the target's current scale
  ScalingActive  False   FailedGetResourceMetric  the HPA was unable to compute the replica count: unable to get metrics for resource cpu: no metrics returned from heapster
Events:
  Type     Reason                        Age                 From                       Message
  ----     ------                        ----                ----                       -------
  Warning  FailedComputeMetricsReplicas  44m (x13 over 50m)  horizontal-pod-autoscaler  failed to get cpu utilization: unable to get metrics for resource cpu: no metrics returned from heapster
  Warning  FailedGetResourceMetric       4s (x101 over 50m)  horizontal-pod-autoscaler  unable to get metrics for resource cpu: no metrics returned from heapster
```

This is what I get from calling the metrics API:

```
$ kubectl get --raw "/apis/metrics.k8s.io/v1beta1/nodes/" | jq
{
  "kind": "NodeMetricsList",
  "apiVersion": "metrics.k8s.io/v1beta1",
  "metadata": {
    "selfLink": "/apis/metrics.k8s.io/v1beta1/nodes/"
  },
  "items": [
    {
      "metadata": {
        "name": "aks-agentpool-10334253-0",
        "selfLink": "/apis/metrics.k8s.io/v1beta1/nodes/aks-agentpool-10334253-0",
        "creationTimestamp": "2018-06-14T22:20:33Z"
      },
      "timestamp": "2018-06-14T22:20:00Z",
      "window": "1m0s",
      "usage": {
        "cpu": "216m",
        "memory": "1208448Ki"
      }
    }
  ]
}

```
There is the main node, but not virtual kubelet's
After request pod's metrics in default namespace:
```
$ kubectl get --raw "/apis/metrics.k8s.io/v1beta1/namespaces/default/pods/" | jq  
{
  "kind": "PodMetricsList",
  "apiVersion": "metrics.k8s.io/v1beta1",
  "metadata": {
    "selfLink": "/apis/metrics.k8s.io/v1beta1/namespaces/default/pods/"
  },
  "items": [
    {
      "metadata": {
        "name": "virtual-kubelet-virtual-kubelet-for-aks-f696c49c-s6j89",
        "namespace": "default",
        "selfLink": "/apis/metrics.k8s.io/v1beta1/namespaces/default/pods/virtual-kubelet-virtual-kubelet-for-aks-f696c49c-s6j89",
        "creationTimestamp": "2018-06-14T22:21:53Z"
      },
      "timestamp": "2018-06-14T22:21:00Z",
      "window": "1m0s",
      "containers": [
        {
          "name": "virtual-kubelet-virtual-kubelet-for-aks",
          "usage": {
            "cpu": "0",
            "memory": "16240Ki"
          }
        }
      ]
    }
  ]
}
```
There is only the pod created for the virtual kubelet.

If I describe my pod I get the following:
```
$ kubectl describe po clientsv3-staging-68df75d698-vqn48 
Name:           clientsv3-staging-68df75d698-vqn48
Namespace:      default
Node:           virtual-kubelet/
Start Time:     Thu, 14 Jun 2018 16:50:35 -0500
Labels:         app=clientsv3-staging
                pod-template-hash=2489318254
Annotations:    <none>
Status:         Running
IP:             40.78.64.123
Controlled By:  ReplicaSet/clientsv3-staging-68df75d698
Containers:
  skyalert3-clients-staging:
    Container ID:   
    Image:          myregistry.azurecr.io/clientsv3-staging:0.0.3
    Image ID:       
    Port:           80/TCP
    Host Port:      0/TCP
    State:          Running
      Started:      Thu, 14 Jun 2018 16:50:35 -0500
    Ready:          True
    Restart Count:  0
    Requests:
      cpu:        100m
    Environment:  <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-lxx7z (ro)
Conditions:
  Type           Status
  Ready          True 
  Initialized    True 
  PodScheduled   True 
Volumes:
  default-token-lxx7z:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-lxx7z
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  kubernetes.io/hostname=virtual-kubelet
Tolerations:     azure.com/aci:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason            Age                From               Message
  ----     ------            ----               ----               -------
  Warning  FailedScheduling  36m (x2 over 36m)  default-scheduler  0/2 nodes are available: 1 MatchNodeSelector, 1 NodeNetworkUnavailable.
  Normal   Scheduled         36m                default-scheduler  Successfully assigned clientsv3-staging-68df75d698-vqn48 to virtual-kubelet

```
Namespace indicates correctness in my metrics request .
Pod's logs:
```
$ kubectl logs clientsv3-staging-68df75d698-vqn48 
*** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
*** Running /etc/my_init.d/30_presetup_nginx.sh...
*** Running /etc/rc.local...
*** Booting runit daemon...
*** Runit started as PID 8
ok: run: /etc/service/nginx-log-forwarder: (pid 25) 1s
```
This output is from my system. I infer there is nothing to show.
This is my deployment:
```
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: clientsv3-staging
  labels:
    app: clientsv3-staging
spec:
  selector:
     matchLabels:
      app: clientsv3-staging
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 10
      maxUnavailable: 9
  minReadySeconds: 5
  template:
    metadata:
      name: clientsv3-staging
      labels:
        app: clientsv3-staging
    spec:
      containers:
      - name: clientsv3-staging
        image: myregistry.azurecr.io/clientsv3-staging:0.0.3
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "0.1"
      imagePullSecrets:
      - name: acr-auth
      nodeSelector: 
        kubernetes.io/hostname: virtual-kubelet
      tolerations:
      - key: azure.com/aci
        effect: NoSchedule

---
apiVersion: v1
kind: Service
metadata:
  name: clientsv3-staging
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: clientsv3-staging

```
I omitted limits for a misknowledge in an error (ContainerLimitGreaterThanContainerGroupTotalRequest, similar to [#143](https://github.com/virtual-kubelet/virtual-kubelet/issues/143)).

I don't know why this is happening. Any suggestion or comment will be appretiated,

### Repo Steps

1. Install metrics server `$ kubectl create -f deploy/1.8+`
2. Install connector `$ helm install "$CHART_URL" --name "$RELEASE_NAME" --set env.azureClientId="$AZURE_CLIENT_ID",env.azureClientKey="$AZURE_CLIENT_SECRET",env.azureTenantId="$AZURE_TENANT_ID",env.azureSubscriptionId="$AZURE_SUBSCRIPTION_ID",env.aciRegion="$ACI_REGION",env.aciResourceGroup="$AZURE_RG",env.nodeName="$NODE_NAME",env.nodeOsType=Linux,env.apiserverCert=$cert,env.apiserverKey=$key,rbac.install=false`
3. Create deploy in AKS `$ kubectl create -f deploy.yaml`
4. Create hpa `$ kubectl autoscale deploy clientsv3-staging --cpu-percent=50 --min=1 --max=2`

`max=2` for testing purposes
