### ISSUE TITLE
Support configuring node taint value and effect

### ISSUE THREAD

**Issue by jlegrone** [virtual-kubelet/virtual-kubelet#259]
Providing a node taint with a key would enable supporting multiple providers with the same key:

```yaml
tolerations:
- key: "virtual-kubelet.github.io/provider"
  value: "azure"
  operator: "Equal"
  effect: "NoSchedule"
```

```yaml
tolerations:
- key: "virtual-kubelet.github.io/provider"
  value: "azurebatch"
  operator: "Equal"
  effect: "NoSchedule"
```

While also being able to schedule workloads on any virtual-kubelet node:

```yaml
tolerations:
- key: "virtual-kubelet.github.io/provider"
  operator: "Exists"
  effect: "NoSchedule"
```

Supporting effect configuration meanwhile would be advantageous for use cases where virtual-kubelet nodes are meant to handle excess workloads, using `PreferNoSchedule`.

Reference: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/#concepts
