### ISSUE TITLE
ACI provider doesn't handle empty environment variables well

### ISSUE THREAD

**Issue by jeremyrickard** [virtual-kubelet/virtual-kubelet#296]
### Environment summary

Provider (e.g. ACI, AWS Fargate, Hyper)
*ACI*

Version (e.g. 0.1, 0.2-beta)
*Master*

K8s Master Info (e.g. AKS, ACS, Bare Metal, EKS)
*AKS* 

Install Method (e.g. Helm Chart, )
*Helm Chart*

### Issue Details
When you create a pod with an environment variable without a value, ACI returns an error:

```
2018/08/03 18:41:55 Error creating pod 'nginx': api call to https://management.azure.com/subscriptions/76fb3144-bc19-4baf-ab79-432d526559b7/resourceGroups/MC_aks-group_vk-cluster_eastus/providers/Microsoft.ContainerInstance/containerGroups/default-nginx?api-version=2018-06-01: got HTTP response status code 400 error code "InvalidEnvironmentVariable": The environment variable 'SOME_EMPTY_ENV' in container 'nginx' of container group 'default-nginx' is invalid. One and only one property of 'value' and 'secureValue' can be specified in an environment variable.
```

The error indicates that _both_ are being sent. In reality, there is _no_ value. `kubectl` / kuberentes allows this, so we need to be able to handle it. 

Additionally, there was an issue introduced during the `SecureValue` PR that resulted in a panic when value was empty. 

### Repo Steps

This YAML:

```
apiVersion: v1
kind: Pod
metadata:
  name: nginx-bad-env2
spec:
  containers:
  - image: nginx
    imagePullPolicy: Always
    name: nginx
    env:
    - name: SOME_EMPTY_ENV
    ports:
    - containerPort: 80
      name: http
      protocol: TCP
    - containerPort: 443
      name: https
  dnsPolicy: ClusterFirst
  nodeSelector:
    kubernetes.io/role: agent
    beta.kubernetes.io/os: linux
    type: virtual-kubelet
  tolerations:
  - key: azure.com/aci
    effect: NoSchedule
```
will result in the error.
