### ISSUE TITLE
Named port resolution doesn't work

### ISSUE THREAD

**Issue by lachie83** [virtual-kubelet/virtual-kubelet#331]
---

### Environment summary

Provider (e.g. ACI, AWS Fargate, Hyper)

ACI

Version (e.g. 0.1, 0.2-beta)

K8s Master Info (e.g. AKS, ACS, Bare Metal, EKS)

AKS

Install Method (e.g. Helm Chart, )

Helm Chart
### Issue Details

A Pod spec with a named port yields a 500 on ACI.

```
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
```

Changing the ports to the container port number resolves the issue. In the API request sent to ACI, the port number is set to 0 until the liveness and readiness probes.

### Repo Steps

Install VK w ACI using Helm
Create a deployment with named port references in liveness and readiness checks scheduled on a ACI backed VK
