### ISSUE TITLE
ACI-Connector Error: The Deployment "nanoserver-iis" is invalid: spec.template.metadata.labels

### ISSUE THREAD

**Issue by razi-rais** [virtual-kubelet/virtual-kubelet#384]
### Environment summary

Provider (e.g. ACI, AWS Fargate, Hyper)
**ACI** 

Version (e.g. 0.1, 0.2-beta)

K8s Master Info (e.g. AKS, ACS, Bare Metal, EKS)
**AKS**

Install Method (e.g. Helm Chart, )
**Helm Chart**

### Issue Details
I am following article (https://docs.microsoft.com/en-us/azure/aks/virtual-kubelet) to run a Pod with windows container in ACI using virtual kubelet but running into the following error.

`The Deployment "nanoserver-iis" is invalid: spec.template.metadata.labels: Invalid value: map[string]string{"app":"nanoserver-iis"}: selector does not match template labels`

The nodes and pod for virtual kubelet are showing up as expected.

![screen shot 2018-10-22 at 3 18 56 pm](https://user-images.githubusercontent.com/7940117/47314137-d1a5f280-d60e-11e8-8a64-764916f6e26c.png)

![screen shot 2018-10-22 at 3 16 10 pm](https://user-images.githubusercontent.com/7940117/47314143-d4084c80-d60e-11e8-83de-2a50dcc3ac63.png)

`virtual-kubelet-windows.yaml`
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aci-helloworld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aci-helloworld
  template:
    metadata:
      labels:
        app: aci-helloworld
    spec:
      containers:
      - name: aci-helloworld
        image: microsoft/aci-helloworld
        ports:
        - containerPort: 80
      nodeSelector:
        kubernetes.io/hostname: virtual-kubelet-virtual-kubelet-linux
      tolerations:
      - key: virtual-kubelet.io/provider
        operator: Equal
        value: azure
        effect: NoSchedule
```
---

### Repo Steps
Run deployment (use the file above).
