### ISSUE TITLE
Pod scheduled at Windows kubelet should not mount any secret volume

### ISSUE THREAD

**Issue by sioakim** [virtual-kubelet/virtual-kubelet#40]
[error.log](https://github.com/virtual-kubelet/virtual-kubelet/files/1583501/error.log)
I use the attached xml to deploy to Windows kubelet.

The windows kubelet should accept nodes for "beta.kubernetes.io/os": "windows"

From "describe node I get:"
Labels:             beta.kubernetes.io/os=windows

I get error:
No nodes are available that match all of the following predicates:: MatchNodeSelector (2), PodToleratesNodeTaints (1).

Full info is attached.

**Comment by sioakim** [comment]
FYI - i just replaced the attached xml with nginx and Linux and worked instantly.

**Comment by robbiezhang** [comment]
@sioakim, can you double check the Linux pod runs on the virtual-kubelet for Linux?

The virtual-kubelet node has the taints "azure.com/aci:NoSchedule". If you want to schedule a pod to the virtual-kubelet, you need to add the following tolerations to your pod spec:

  tolerations:
  - key: azure.com/aci
    effect: NoSchedule

Seems like the example is missing this section. I'll update it.

**Comment by sioakim** [comment]
You are right - the linux one started on the k8s node. I had some other example apparently that had started it on the ACI.

Can you please provide an example for Windows as well?

The below doesn't work for example:

```
apiVersion: v1
kind: Pod
metadata:
  name: iis
spec:
  containers:
  - image: microsoft/iis
    imagePullPolicy: Always
    name: iis
    resources:
      requests:
        memory: 4G
        cpu: 2
    ports:
    - containerPort: 80
      name: http
      protocol: TCP
    - containerPort: 443
      name: https
  dnsPolicy: ClusterFirst
  nodeName: virtual-kubelet-aciconnector-win
  tolerations:
  - key: azure.com/aci
    effect: NoSchedule
```
