### ISSUE TITLE
[ACI] Support ImagePullSecret without Username/Password

### ISSUE THREAD

**Issue by vedant-khandelwal** [virtual-kubelet/virtual-kubelet#411]
---

### Environment summary

Provider (e.g. ACI, AWS Fargate, Hyper)
ACI

Version (e.g. 0.1, 0.2-beta)
0.5.0

K8s Master Info (e.g. AKS, ACS, Bare Metal, EKS)
AKS

Install Method (e.g. Helm Chart, )
Helm Chart with the following command:
```
helm install "$CHART_URL" --name "$RELEASE_NAME" \
  --set provider=azure \
  --set providers.azure.targetAKS=true \
  --set providers.azure.vnet.enabled=true \
  --set providers.azure.vnet.subnetName=$ACI_SUBNET_NAME \
  --set providers.azure.vent.subnetCidr=$ACI_SUBNET_RANGE \
  --set providers.azure.vnet.clusterCidr=$CLUSTER_SUBNET_RANGE \
  --set providers.azure.vnet.kubeDnsIp=$KUBE_DNS_IP \
  --set providers.azure.masterUri=$MASTER_URI
```

### Issue Details
The connector is deployed with the AKS vnet configured for the container instances.

Pod goes into `ProviderFailed` state with the describe pod showing the following error
```
api call to https://management.azure.com/subscriptions/e144ac7a-5041-4688-960f-fe4d556070e1/resourceGroups/MC_aks_aks_eastus/providers/Microsoft.ContainerInstance/containerGroups/default-aci-pod-79649c5958-7pqcg?api-version=2018-09-01: got HTTP response status code 400 error code "InvalidRequestContent": The request content was invalid and could not be deserialized: 'Required property 'username' not found in JSON. Path 'properties.imageRegistryCredentials[0]', line 1, position 1328.'.
```
This is an RBAC disable cluster and the pod has an imagePullSecret property set. The pod runs successfully if the imagePullSecret is removed.

### Repo Steps
Follow steps to deploy an AKS cluster with vnet, and use the same vnet (another subnet) for aci connector.
Ref:  https://docs.microsoft.com/en-us/azure/container-instances/container-instances-vnet
Ref: https://github.com/virtual-kubelet/virtual-kubelet/tree/master/providers/azure#deploy-virtual-kubelet

Create a deployment/pod resource in the cluster with an `imagePullSecret`.

Note: Make sure the pod is assigned to the virtual-node.

**Comment by robbiezhang** [comment]
@vedant-khandelwal Can you provide your pod spec, and the image pull secret spec? I suspect the image pull secret is not set properly.

**Comment by vedant-khandelwal** [comment]
That's not the case since when I reassign that pod to the AKS node using nodeSelector, it runs just fine. For sake of reproducing the issue, you can try using the sample template provided in the Azure docs:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aci-helloworld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aci-helloworld
  template:
    metadata:
      labels:
        app: aci-helloworld
    spec:
      imagePullSecrets:
        -
          name: "falkonry"
      containers:
      - name: aci-helloworld
        image: microsoft/aci-helloworld
        ports:
        - containerPort: 80
      nodeSelector:
        beta.kubernetes.io/os: linux
        kubernetes.io/role: agent
        type: virtual-kubelet
```

**Comment by robbiezhang** [comment]
VK uses the standard way to fetch the secret from the k8s, which expects that the secret in the imagePullSecrets exist.
https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/#create-a-secret-in-the-cluster-that-holds-your-authorization-token
I suspect that kubelet just ignores the non-existing secrets in the pod spec, but need investigate it. That's why the sample spec work I guess.
Please also notice that AKS has an optimization to use the SPN to fetch the image from ACR. See #192

**Comment by robbiezhang** [comment]
Your example doesn't have the tolerations, which didn't schedule in my cluster. It works fine for me once I append the tolerations. Here is the working version for me:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aci-helloworld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aci-helloworld
  template:
    metadata:
      labels:
        app: aci-helloworld
    spec:
      imagePullSecrets:
        - name: vk-registry
      containers:
      - name: aci-helloworld
        image: microsoft/aci-helloworld
        ports:
        - containerPort: 80
      nodeSelector:
        beta.kubernetes.io/os: linux
        kubernetes.io/role: agent
        type: virtual-kubelet
      tolerations:
      - key: virtual-kubelet.io/provider
        operator: Exists
      - key: azure.com/aci
        effect: NoSchedule
```
Here is my secret spec. I've removed the content. I created it by using the link I provided in my previous reply.

```yaml
apiVersion: v1
data:
  .dockerconfigjson: 
...
kind: Secret
metadata:
  name: vk-registry
  namespace: default
type: kubernetes.io/dockerconfigjson
```
Can you inspect the secret?
https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/#inspecting-the-secret-regcred

Note that ACI provider supports 2 types of secret:
https://github.com/virtual-kubelet/virtual-kubelet/blob/023fd1214aeccc3ecc164805aaac563dbadd1b90/providers/azure/aci.go#L984-L987
