### ISSUE TITLE
configmaps volume mounts not supported?

### ISSUE THREAD

**Issue by AceHack** [virtual-kubelet/virtual-kubelet#441]
The following works:

```
        volumeMounts:
        - name: platform-capability-secrets
          mountPath: /etc/global/secrets/capability
      volumes:
      - name: platform-capability-secrets
        secret:
          secretName: platform-capability-secrets.json
          optional: false
```

The following is broken and fails:
```
        volumeMounts:
        - name: platform-capability-config
          mountPath: /etc/global/configuration/capability
      volumes:
      - name: platform-capability-config
        configMap:
          name: platform-capability-config.json
          optional: false
```
