### ISSUE TITLE
VK crashes when populating env var from non-existing secret

### ISSUE THREAD

**Issue by Smithx10** [virtual-kubelet/virtual-kubelet#444]
---

### Environment summary

Provider (triton)

Version (0)

K8s Master Info (minikube)

### Issue Details
If you provide a secretKeyRef that doesn't exist VK dumps.

```
/usr/local/go/src/runtime/asm_amd64.s:1333
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x108 pc=0x19d31c6]

goroutine 64 [running]:
github.com/virtual-kubelet/virtual-kubelet/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /home/smith/go/src/github.com/virtual-kubelet/virtual-kubelet/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x108                                                                                                                       
panic(0x1cd5340, 0x3aa7af0)
        /usr/local/go/src/runtime/panic.go:513 +0x1b9
github.com/virtual-kubelet/virtual-kubelet/vkubelet.(*Server).populateEnvironmentVariables(0xc0003aa230, 0xc000cc5880, 0xc0002e0c60, 0x11)                                                                                                                   
        /home/smith/go/src/github.com/virtual-kubelet/virtual-kubelet/vkubelet/env.go:41 +0x216
github.com/virtual-kubelet/virtual-kubelet/vkubelet.(*Server).createOrUpdatePod(0xc0003aa230, 0x23ba960, 0xc000b05b30, 0xc000cc5880, 0x0, 0x0)                                                                                                               
        /home/smith/go/src/github.com/virtual-kubelet/virtual-kubelet/vkubelet/pod.go:43 +0x16e
github.com/virtual-kubelet/virtual-kubelet/vkubelet.(*PodController).syncPodInProvider(0xc000332be0, 0x23ba960, 0xc000af7f20, 0xc000cc5880, 0x0, 0x0)                                                                                                        
        /home/smith/go/src/github.com/virtual-kubelet/virtual-kubelet/vkubelet/podcontroller.go:286 +0x2c4
github.com/virtual-kubelet/virtual-kubelet/vkubelet.(*PodController).syncHandler(0xc000332be0, 0x23ba960, 0xc000af7ec0, 0xc000c30d20, 0x1f, 0x0, 0x0)                                                                                                        
        /home/smith/go/src/github.com/virtual-kubelet/virtual-kubelet/vkubelet/podcontroller.go:257 +0x748
github.com/virtual-kubelet/virtual-kubelet/vkubelet.(*PodController).processNextWorkItem.func1(0xc000332be0, 0x23ba960, 0xc000af7e60, 0xc000659800, 0x1beff80, 0xc000170580, 0x0, 0x0)                                                                       
        /home/smith/go/src/github.com/virtual-kubelet/virtual-kubelet/vkubelet/podcontroller.go:195 +0x1af
github.com/virtual-kubelet/virtual-kubelet/vkubelet.(*PodController).processNextWorkItem(0xc000332be0, 0x23ba960, 0xc000af7e60, 0x215a406, 0x2, 0x0)                                                                                                         
        /home/smith/go/src/github.com/virtual-kubelet/virtual-kubelet/vkubelet/podcontroller.go:209 +0x20b
github.com/virtual-kubelet/virtual-kubelet/vkubelet.(*PodController).runWorker(0xc000332be0, 0x23ba8a0, 0xc000a0c100, 0x215a406, 0x2)                                                                                                                        
        /home/smith/go/src/github.com/virtual-kubelet/virtual-kubelet/vkubelet/podcontroller.go:155 +0x53
github.com/virtual-kubelet/virtual-kubelet/vkubelet.(*PodController).Run.func1()
        /home/smith/go/src/github.com/virtual-kubelet/virtual-kubelet/vkubelet/podcontroller.go:142 +0x7e
github.com/virtual-kubelet/virtual-kubelet/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc000a26de0)
        /home/smith/go/src/github.com/virtual-kubelet/virtual-kubelet/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x54                                                                                                                             
github.com/virtual-kubelet/virtual-kubelet/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000a26de0, 0x3b9aca00, 0x0, 0x1, 0xc000056540)                                                                                                            
        /home/smith/go/src/github.com/virtual-kubelet/virtual-kubelet/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134 +0xbe                                                                                                                             
github.com/virtual-kubelet/virtual-kubelet/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc000a26de0, 0x3b9aca00, 0xc000056540)                                                                                                                            
        /home/smith/go/src/github.com/virtual-kubelet/virtual-kubelet/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d                                                                                                                              
created by github.com/virtual-kubelet/virtual-kubelet/vkubelet.(*PodController).Run
        /home/smith/go/src/github.com/virtual-kubelet/virtual-kubelet/vkubelet/podcontroller.go:140 +0x223
```


### Repo Steps


Configure a pod / replicaset / or deployment and provide a secretKeyRef that doesn't exist.

```
    spec:                                                                                                                                                                                                                                                     
      restartPolicy: Always                                                                                                                                                                                                                                   
      containers:                                                                                                                                                                                                                                             
      - image: c239a01f-5fe9-456f-8f92-53f5b7efd53d                                                                                                                                                                                                           
        name: consul                                                                                                                                                                                                                                          
        ports:                                                                                                                                                                                                                                                
          - containerPort: 8500                                                                                                                                                                                                                               
            protocol: TCP                                                                                                                                                                                                                                     
            name: consul                                                                                                                                                                                                                                      
          - containerPort: 22                                                                                                                                                                                                                                 
            name: ssh                                                                                                                                                                                                                                         
        envFrom:                                                                                                                                                                                                                                              
          - configMapRef:                                                                                                                                                                                                                                     
              name: consul-config                                                                                                                                                                                                                             
        env:                                                                                                                                                                                                                                                  
        - name: SECRET_USERNAME                                                                                                                                                                                                                               
          valueFrom:                                                                                                                                                                                                                                          
           secretKeyRef:                                                                                                                                                                                                                                      
              name: mysecrets                                                                                                                                                                                                                                 
              key: username     
```
