### ISSUE TITLE
ACI provider prematurely reports pods as ready when they, in fact, are unreachable

### ISSUE THREAD

**Issue by krancour** [virtual-kubelet/virtual-kubelet#448]
---

### Environment summary

Provider (e.g. ACI, AWS Fargate, Hyper)

ACI

Version (e.g. 0.1, 0.2-beta)

v0.7.4

K8s Master Info (e.g. AKS, ACS, Bare Metal, EKS)

AKS (k8s v1.11.5)

Install Method (e.g. Helm Chart, )

Helm chart-- the virtual-kubelet-for-aks chart, specifically

### Issue Details

Consistently, I can observe that pods scheduled to VK remain unreachable for sometimes as long as approximately two minutes _after_ they've been assigned IPs, gone into a ready condition, and even been selected as endpoints for a service.

### Repo Steps

Apply this manifest to your cluster:

```
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: http
  selector:
    app: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 0
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - name: http 
          containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
      nodeSelector:
        kubernetes.io/role: agent
        beta.kubernetes.io/os: linux
        type: virtual-kubelet
      tolerations:
      - key: virtual-kubelet.io/provider
        operator: Exists
      - key: azure.com/aci
        effect: NoSchedule
```

1. Wait for the `nginx` service to get an external IP.

    ```
    watch kubectl get svc nginx
    ```

1. Watch `nginx` endpoints.

    In a separate terminal:

    ```
    watch kubectl get endpoints nginx
    ```

    (There will be none, initially.)

1. Watch nginx pods.

    In a separate terminal:

    ```
    watch kubectl get pods -l app=nginx
    ```

1. Scale the `nginx` deployment to one replica.

    In a separate terminal:

    ```
    kubectl scale deployment nginx --replicas 1
    ```

1. Wait for the pod to appear ready. (See no. 3)

1. Wait for the pod's IP to appear among the `nginx` endpoints. (See no. 2)

1. Curl the service using its external IP.

    ```
    curl -s -o /dev/null -w "%{http_code}" http://<service external IP>
    ```

    Observe that either:

      a. A successful response will take quite some time

      OR

      b. The request will time out with an "http response code" (not really) of 000, which indicates a dialing error.

    Repeated attempts to curl the IP will eventually be successful.

1. Scale the deployment back down to zero:

    ```
    kubectl scale deployment nginx --replicas 0
    ```

1. Scale the deployment back up to one:

    ```
    kubectl scale deployment nginx --replicas 0
    ```

1. Wait for the pod to appear ready. (See no. 3)

1. Wait for the pod's IP to appear among the `nginx` endpoints. (See no. 2)

1. Curl the pod _directly_ (it has a public IP, after all).

    ```
    curl -s -o /dev/null -w "%{http_code}" http://<pod's public IP>
    ```

    Observe that either:

      a. A successful response will take quite some time

      OR

      b. The request will time out with an "http response code" (not really) of 000, which indicates a dialing error.

    Repeated attempts to curl the IP will eventually be successful.

All of this would strongly indicate that VK (or ACI itself?) prematurely reports pods to be "ready," when, in fact, they're not yet accessible via their assigned IPs.
