### ISSUE TITLE
ACI support hostAliases

### ISSUE THREAD

**Issue by dannymyers** [virtual-kubelet/virtual-kubelet#467]
### Environment summary

Provider ACI
Version v1.11 (?)
K8s Master Info AKS
Install Method Azure Portal

### Issue Details

[hostAliases](https://kubernetes.io/docs/concepts/services-networking/add-entries-to-pod-etc-hosts-with-host-aliases/) do not work when using virtual-kubelets.

### Repo Steps

```
apiVersion: v1
kind: Pod
metadata:
  name: hostaliases-pod
spec:
  restartPolicy: Never
  hostAliases:
  - ip: "127.0.0.1"
    hostnames:
    - "foo.local"
    - "bar.local"
  - ip: "10.1.2.3"
    hostnames:
    - "foo.remote"
    - "bar.remote"
  containers:
  - name: cat-hosts
    image: busybox
    command:
    - cat
    args:
    - "/etc/hosts"
  nodeSelector:
    kubernetes.io/role: agent
    beta.kubernetes.io/os: linux
    type: virtual-kubelet
  tolerations:
  - key: virtual-kubelet.io/provider
    operator: Exists
  - key: azure.com/aci
    effect: NoSchedule
```

`kubectl logs hostaliases-pod`

Notice how host aliases are not in the output.
