### ISSUE TITLE
Can't mount config map to Virtual Kubelet

### ISSUE THREAD

**Issue by patnaikshekhar** [virtual-kubelet/virtual-kubelet#523]
---

### Environment summary

Provider (e.g. ACI, AWS Fargate, Hyper)
ACI

Version (e.g. 0.1, 0.2-beta)
 v1.13.1-vk-v0.7.4-44

K8s Master Info (e.g. AKS, ACS, Bare Metal, EKS)
AKS

Install Method (e.g. Helm Chart, )
kubectl apply

### Issue Details
When trying to mount a config map to a Pod in a virtual kubelet the provisioning fails with the error "ProviderFailed". Running a describe or logs on the pod does not yield any additional information.

### Repo Steps
```
1. Create a configmap
apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: 2016-02-18T18:52:05Z
  name: main-config
data:
  function.py: |
    def main():
      print "test"
  ui.properties: |
    color = purple
```
2. Create a Pod which mounts the config map as a volume
```
apiVersion: v1
kind: Pod
metadata:
  name: main-pod
spec:
  containers:
    - name: goapp
      image: patnaikshekhar/vkubletconfigmaptest:1
      ports:
      - containerPort: 8000
      volumeMounts:
      - name: myconfig
        mountPath: /kubeless
  volumes:
  - name: myconfig
    configMap:
      defaultMode: 420
      name: main-config
  nodeSelector:
    beta.kubernetes.io/os: linux
    kubernetes.io/role: agent
    type: virtual-kubelet
  tolerations:
  - key: virtual-kubelet.io/provider
    operator: Equal
    value: azure
    effect: NoSchedule
```
3. Run kubectl apply to create the config map and pod

The pod will schedule correctly on a non VK node.
