### ISSUE TITLE
Init containers not working properly for ACI provider

### ISSUE THREAD

**Issue by radu-matei** [virtual-kubelet/virtual-kubelet#530]
---

### Environment summary

Provider: ACI

Version: vk-v0.7.4-44-g4f3bd20e-dev

K8s Master Info: AKS, v1.12.5

Install Method: Helm chart

### Issue Details
`init` containers with shared `emptyDir` volumes do not work properly. 

Not sure if this is a limitation of ACI, or VK mishandles `init` containers, but I didn't seem to find anything about this in the VK documentation -- sorry if I missed it.

### Repo Steps

- pod with an `init` container that works properly on a Kubernetes node:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: init-demo-node
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
      volumeMounts:
        - name: workdir
          mountPath: /usr/share/nginx/html
  # These containers are run during pod initialization
  initContainers:
    - name: install
      image: busybox
      command:
        - wget
        - "-O"
        - "/work-dir/index.html"
        - http://kubernetes.io
      volumeMounts:
        - name: workdir
          mountPath: "/work-dir"
  dnsPolicy: Default
  volumes:
    - name: workdir
      emptyDir: {}
```

- if we `kubectl exec` inside this pod and `curl localhost` (you first need to add `curl`), we get the Kubernetes landing page (this is what the `init` container does, downloads the landing page and places it in the shared `emptyDir`):

```bash
root@init-demo-node:/:$ curl localhost  
<!doctype html><html id=home lang=en><head><title>Production-Grade Container Orchestration - Kubernetes</title><meta name=viewport content="width=device-width,initial-scale=1"><link rel="shortcut icon" type=image/png href=/images/favicon.png><link rel=stylesheet href=/css/base_fonts.css><link rel=stylesheet href=/css/styles.css><link rel=stylesheet href=/css/jquery-ui.min.css><link rel=stylesheet href=/css/sweetalert.min.css><link rel=stylesheet href=/css/callouts.css><link rel=stylesheet href=/css/custom-jekyll/tags.css><meta name=description content="Kubernetes (k8s) is an open-source system for automating deployment, scaling, and management of containerized applications. It groups containers that make up an application into logical units for easy management and discovery. Kubernetes builds upon 15 years of experience of running production workloads at Google, combined with best-of-breed ideas and practices from the community
```

- modifying the same pod definition to work with VK (adding taints and resources):

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: init-demo
spec:
  containers:
    - name: nginx
      image: nginx
      resources:
        requests:
          memory: 1G
          cpu: 1
      ports:
        - containerPort: 80
      volumeMounts:
        - name: workdir
          mountPath: /usr/share/nginx/html
  # These containers are run during pod initialization
  initContainers:
    - name: install
      image: busybox
      command:
        - wget
        - "-O"
        - "/work-dir/index.html"
        - http://kubernetes.io
      volumeMounts:
        - name: workdir
          mountPath: "/work-dir"
  dnsPolicy: ClusterFirst
  nodeSelector:
    kubernetes.io/role: agent
    beta.kubernetes.io/os: linux
    type: virtual-kubelet
  tolerations:
    - key: virtual-kubelet.io/provider
      operator: Exists
    - key: azure.com/aci
      effect: NoSchedule
  volumes:
    - name: workdir
      emptyDir: {}
```
- doing the same thing on the pod scheduled by VK:

```bash
root@wk-caas-a8fdab84b97a4ab29e364c20bdbadafa:/$ curl localhost
<html>
<head><title>403 Forbidden</title></head>
<body>
<center><h1>403 Forbidden</h1></center>
<hr><center>nginx/1.15.8</center>
</body>
</html>
```
