### ISSUE TITLE
Pod status is inconsistent with containers status cause a nil pointer dereference error.

### ISSUE THREAD

**Issue by zlseu-edu** [virtual-kubelet/virtual-kubelet#583]
---

### Environment summary

Provider : Alibaba

Version : master

K8s Master Info : ACS

Install Method : kubectl

### Issue Details

Examples are as below. `Nginx` Container will exit after executing the command `ls -l`, all pods will in `CrashLoopBackOff` state. There has a small probability of `VK` crash again and again.

``` yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 10
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        command: ["/bin/sh"]
        args: ["ls", "-l"]
        ports:
        - containerPort: 80
      nodeSelector:
        kubernetes.io/role: agent
        beta.kubernetes.io/os: linux
        type: virtual-kubelet
      tolerations:
      - key: virtual-kubelet.io/provider
        operator: Exists
```

### Repo Steps

Crash info show a dereference nil poniter error in `c.State.Running.StartedAt` of file `vkubelet/pod.go` line `200` :

``` go
// Only change the status when the pod was already up
// Only doing so when the pod was successfully running makes sure we don't run into race conditions during pod creation.
if pod.Status.Phase == corev1.PodRunning || pod.ObjectMeta.CreationTimestamp.Add(time.Minute).Before(time.Now()) {
    // Set the pod to failed, this makes sure if the underlying container implementation is gone that a new pod will be created.
    pod.Status.Phase = corev1.PodFailed
    pod.Status.Reason = "NotFound"
    pod.Status.Message = "The pod status was not found and may have been deleted from the provider"
    for i, c := range pod.Status.ContainerStatuses {
        // Skip waiting and Terminated status
        if c.State.Waiting != nil || c.State.Terminated != nil {
            continue
        }
        pod.Status.ContainerStatuses[i].State.Terminated = &corev1.ContainerStateTerminated{
            ExitCode:    -137,
            Reason:      "NotFound",
            Message:     "Container was not found and was likely deleted",
            FinishedAt:  metav1.NewTime(time.Now()),
            StartedAt:   c.State.Running.StartedAt,
            ContainerID: c.ContainerID,
        }
        pod.Status.ContainerStatuses[i].State.Running = nil
    }
}
```

It seems that `a pod in running state` doesn't mean that `its container in running state` too!
