### ISSUE TITLE
Pod In "NotFound" Status Virtual Kubelet

### ISSUE THREAD

**Issue by dannymyers** [virtual-kubelet/virtual-kubelet#689]
---

### Environment summary

virtual-node-aci-linux   `v1.13.1-vk-v0.9.0-1-g7b92d1ee-dev`
AKS  `1.12.8`
Terraform/Helm

### Issue Details

We’re getting NotFound our pods that we are trying to run on virtual nodes.

```
NAME                                                 READY     STATUS     RESTARTS   AGE       IP        NODE
somejob-47z22   0/1       NotFound   0          13m       <none>    virtual-node-aci-linux
somejob-5ps2f   0/1       NotFound   0          5m        <none>    virtual-node-aci-linux
somejob-5wq6t   0/1       NotFound   0          11m       <none>    virtual-node-aci-linux
somejob-dw7rc   0/1       NotFound   0          15m       <none>    virtual-node-aci-linux
somejob-hkqs9   0/1       NotFound   0          10m       <none>    virtual-node-aci-linux
somejob-rl7h6   0/1       NotFound   0          16m       <none>    virtual-node-aci-linux

```

Here is what I see in the aci-connector-linux logs:

```
time="2019-07-02T15:26:38Z" level=warning msg="skipping sync of pod [[[[\"jobs/somejob-hkqs9\" \"Failed\"]]]] in %!q(MISSING) phase" key=jobs/somejob-hkqs9 method=syncPodInProvider name=somejob-hkqs9 namespace=jobs node=virtual-node-aci-linux operating
System=Linux phase=Failed provider=azure reason=NotFound uid=<GUID> workerId=10
time="2019-07-02T15:30:36Z" level=warning msg="requeuing [[\"jobs/somejob-5ps2f\" \"failed to sync pod \\\"jobs/somejob-5ps2f\\\" in the provider: unsupported fieldPath: status.podIP\"]] due to failed sync: %!v(MISSING)" key=jobs/somejob-5ps2f method=h
andleQueueItem namespace= node=virtual-node-aci-linux operatingSystem=Linux provider=azure workerId=10

```
### Repo Steps

I'm not sure how to repro this. Our other clusters don't have this problem and they were released with the same TF/Helm code.

**Comment by cpuguy83** [comment]
`NotFound` is set when the provider no longer has the pod, so generally it's been deleted.
Did you check if the containers exist in ACI?

**Comment by dannymyers** [comment]
@cpuguy83 I am creating a kubernetes job which then spins up a pod. I don't see anything being 
created in ACI. It goes directly from Scheduled->NotFound.

kubectl describe po somejob-4vq9r -n jobs
```
Name:               somejob-4vq9r
Namespace:          jobs
Priority:           0
PriorityClassName:  <none>
Node:               virtual-node-aci-linux/
Labels:             controller-uid=GUID
                    job-name=somejob
Annotations:        <none>
Status:             Failed
Reason:             NotFound
Message:            The pod status was not found and may have been deleted from the provider
<SNIP>
Type    Reason     Age   From               Message
----    ------     ----  ----               -------
Normal  Scheduled  2m    default-scheduler  Successfully assigned jobs/somejob-4vq9r to virtual-node-aci-linux
```

**Comment by cpuguy83** [comment]
Can you share the pod spec?
The error seems to be: `unsupported fieldPath: status.podIP`
This is from the fieldpath package in k/k.

**Comment by cpuguy83** [comment]
Perhaps we need to also make sure not set set `NotFound` if the pod is already in a failed status.

**Comment by dannymyers** [comment]
@cpuguy83  here's the podspec

```
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  generateName: somejob-SOME_GUID-
  labels:
    controller-uid: OTHER_GUID
    job-name: somejob-SOME_GUID
  ownerReferences:
  - apiVersion: batch/v1
    blockOwnerDeletion: true
    controller: true
    kind: Job
    name: somejob-SOME_GUID
    uid: OTHER_GUID
  selfLink: /api/v1/namespaces/jobs/pods/somejob-SOME_GUID-x79tr
spec:
  containers:
  - env:
    - name: RunKey
      value: SOME_GUID
    - name: ClientKey
      value: "1"
    - name: CpuCores
      value: "1"
    - name: GpuCores
      value: "0"
    - name: MemoryInGigabytes
      value: "1"
    - name: UseVirtualNodes
      value: "True"
    - name: NodeName
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: spec.nodeName
    - name: PodName
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    - name: PodNamespace
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
    - name: PodIPAddress
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.podIP
    - name: PodServiceAccount
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: spec.serviceAccountName
    - name: BlobName
      value: ABC.zip
    - name: BaseDirectory
      value: /mnt
    image: SOME_ACR.azurecr.io/somerepo:sometag
    imagePullPolicy: Always
    name: somejob-SOME_GUID
    resources:
      limits:
        cpu: "1"
        memory: 1G
      requests:
        cpu: "1"
        memory: 1G
    securityContext:
      allowPrivilegeEscalation: false
      privileged: false
      procMount: Default
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 1000
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /mnt
      name: azure
    - mountPath: /etc/secrets
      name: secrets
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-something
      readOnly: true
  dnsPolicy: ClusterFirst
  imagePullSecrets:
  - name: image-pull-secret
  nodeName: virtual-node-aci-linux
  nodeSelector:
    beta.kubernetes.io/os: linux
    kubernetes.io/role: agent
    type: virtual-kubelet
  priority: 0
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 1000
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - key: virtual-kubelet.io/provider
    operator: Exists
  - effect: NoSchedule
    key: azure.com/aci
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - azureFile:
      secretName: data-file-share-secret
      shareName: data
    name: azure
  - name: secrets
    secret:
      defaultMode: 420
      secretName: some-secrets
  - name: default-token-something
    secret:
      defaultMode: 420
      secretName: default-token-something
status:
  phase: Pending
  qosClass: Guaranteed
```
