### ISSUE TITLE
virtual-kubelet dns resolution is not working

### ISSUE THREAD

**Issue by mslonli** [virtual-kubelet/virtual-kubelet#739]
---

### Environment summary

Provider (e.g. ACI, AWS Fargate)
Azure
Version (e.g. 0.1, 0.2-beta)

K8s Master Info (e.g. AKS, ACS, Bare Metal, EKS)
AKS
Install Method (e.g. Helm Chart, )
Helm Chart
### Issue Details
Azure Vote Demo app doesn't work after deployed the front-end and back-end apps to virtual node AKS. 
With the following config, the backend pod cannot be curled. After changing the value to full path "azure-vote-back.default.svc.cluster.local", the backend can be curled.
- name: azure-vote-front
        image: microsoft/azure-vote-front:v1
        ports:
        - containerPort: 80
        env:
        - name: REDIS
          value: "azure-vote-back"

 It might be caused by the issue of DNS resolution in virtual-kubelet 
 It doesn't search dns in the folllowing domain. 
searches:
      - default.svc.cluster.local
      - svc.cluster.local 
      - cluster.local

### Repo Steps
1. Create a virtual node on AKS by following this wiki (https://docs.microsoft.com/en-us/azure/aks/virtual-nodes-cli)
2. Deploy the front-end and back-end services to the virtual node with the following config.
3. Curl the backend from front-end not working.

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-vote-back
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azure-vote-back
  template:
    metadata:
      labels:
        app: azure-vote-back
    spec:
      nodeSelector:
        kubernetes.io/role: agent
        beta.kubernetes.io/os: linux
        type: virtual-kubelet
      containers:
      - name: azure-vote-back
        image: redis
        ports:
        - containerPort: 6379
          name: redis
      tolerations:
      - key: virtual-kubelet.io/provider
        operator: Exists
        effect: NoSchedule
---
apiVersion: v1
kind: Service
metadata:
  name: azure-vote-back
spec:
  ports:
  - port: 6379
  selector:
    app: azure-vote-back
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-vote-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azure-vote-front
  template:
    metadata:
      labels:
        app: azure-vote-front
    spec:
      nodeSelector:
        kubernetes.io/role: agent
        beta.kubernetes.io/os: linux
        type: virtual-kubelet
      containers:
      - name: azure-vote-front
        image: microsoft/azure-vote-front:v1
        ports:
        - containerPort: 80
        env:
        - name: REDIS
          value: "azure-vote-back"
      tolerations:
      - key: virtual-kubelet.io/provider
        operator: Exists
        effect: NoSchedule



```
