### ISSUE TITLE
Support for Azure File share in linux ACI containers

### ISSUE THREAD

**Issue by arkoc** [virtual-kubelet/virtual-kubelet#832]
### Environment summary

Provide: ACI
K8s Master Info: AKS

### Issue Details
Couldn't found any documentation describing are Azure File shares supported for Linux ACI containers or no, so I tried following:

```
apiVersion: v1
kind: Pod
metadata:
  name: aci-helloworld
spec:
  containers:
  - name: aci-helloworld
    image: microsoft/aci-helloworld
    stdin: true 
    tty: true 
    ports:
    - containerPort: 80
    volumeMounts:
    - name: azure
      mountPath: /mnt/azure
  nodeSelector:
    kubernetes.io/role: agent
    beta.kubernetes.io/os: linux
    type: virtual-kubelet
  tolerations:
   - key: virtual-kubelet.io/provider
     operator: Exists
  volumes:
  - name: azure
    azureFile:
      secretName: azure-storage-secret
      shareName: test
      readOnly: false
```

### Repo Steps

1. Apply pod described above.
2. Wait 10+ minutes.

Expected Result:
Pod should be up and with Azure file mounted.

Actual Result:
Pod stack at status Creating.

This is output of `kubectl describe pod aci-helloworld`

```
Name:         aci-helloworld
Namespace:    default
Priority:     0
Node:         virtual-node-aci-linux/
Labels:       <none>
Annotations:  Status:  Unknown
IP:
IPs:          <none>
Containers:
  aci-helloworld:
    Container ID:   aci://a91e8c9961d494289a1617c4bac376c6452782f9ba015a5654d2272fc53094bd
    Image:          microsoft/aci-helloworld
    Image ID:
    Port:           80/TCP
    Host Port:      0/TCP
    State:          Waiting
      Reason:       Creating
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /mnt/azure from azure (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-xxx (ro)
Volumes:
  azure:
    Type:        AzureFile (an Azure File Service mount on the host and bind mount to the pod)
    SecretName:  azure-storage-secret
    ShareName:   test
    ReadOnly:    false
  default-token-xxx:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-xxx
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  beta.kubernetes.io/os=linux
                 kubernetes.io/role=agent
                 type=virtual-kubelet
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
                 virtual-kubelet.io/provider
Events:
  Type    Reason     Age   From               Message
  ----    ------     ----  ----               -------
  Normal  Scheduled  13m   default-scheduler  Successfully assigned default/aci-helloworld to virtual-node-aci-linux
```

ACI Container status in the azure portal is `Unhealthy`. 

I can see a bunch of same warnings shown below from the output of `az container show ... ` command:

```
      {
        "count": 1,
        "firstTimestamp": "2020-06-02T16:57:03+00:00",
        "lastTimestamp": "2020-06-02T16:57:03+00:00",
        "message": "Provision network interface failed for \"GUID\"/\"virtual-node-aci\"/\"GUID\": Timeout.",
        "name": "ProvisionNetworkInterface",
        "type": "Warning"
      }
```
