### ISSUE TITLE
Doc needed - How to secure  communication between vk and Api server 

### ISSUE THREAD

**Issue by sureshsankaran** [virtual-kubelet/virtual-kubelet#864]
Could you please share/point to any document on the recommendation to setup secure communication between api server and vk (and vk to api server as well) ? I am planning on using vk for this scenario: cloud vendors managed k8s cluster with raspberry pi based vk. So all the details to keep this channel between endpoints are appreciated.

Thanks

**Comment by pires** [comment]
Hello @sureshsankaran! You can establish and secure your VK-apiserver communications with a kubeconfig that ensures the API certificate is valid and that VK uses a client certificate the apiserver recognizes too.

Here's an example that works for me when running one VK provider called `systemk`

```yaml
apiVersion: v1
clusters:
- cluster:
    server: https://192.168.64.17:8443
    insecure-skip-tls-verify: true
  name: minikube
contexts:
- context:
    cluster: minikube
    user: systemk
  name: systemk
current-context: systemk
kind: Config
preferences: {}
users:
- name: systemk
  user:
    client-certificate: systemk.crt
    client-key: systemk.key
```
